---
name: Create and publish Container Image

on:
  push:
    branches: ['release']

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: expeditioneer/fluentoo-build-environment
  REGISTRY: docker.io

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Build fluentoo-containerized-build-environment container image
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
