---
name: Create and publish Container Image

on:
  push:
    branches: ['release']
  schedule:
    - cron: "30 23 * * SUN"

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: expeditioneer/fluentoo-build-environment
  REGISTRY: docker.io

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Build fluentoo-build-environment container image
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels)
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Push image to ${{ env.REGISTRY }}
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/quay-user
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
